- hosts: localhost
  tasks:
    - name: Update apt cache
      become: true
      apt:
        update_cache: yes

    - name: Install required packages
      become: true
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - git-core 
        - curl 
        - zlib1g-dev 
        - build-essential 
        - libssl-dev 
        - libreadline-dev 
        - libyaml-dev 
        - libsqlite3-dev 
        - sqlite3 
        - libxml2-dev 
        - libxslt1-dev 
        - libcurl4-openssl-dev 
        - python-software-properties 
        - libffi-dev 
        - nodejs

    - name: clone rbenv
      git:
        repo: git://github.com/rbenv/rbenv.git
        dest: /home/vagrant/.rbenv

    - name: setup rbenv
      shell: "{{ item }}"
      args:
        chdir: /home/vagrant
        executable: /bin/bash
      with_items:
        - echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
        - echo 'eval "$(rbenv init -)"' >> ~/.bashrc
        - exec $SHELL

    - name: clone ruby-build
      git:
        repo: git://github.com/rbenv/ruby-build.git
        dest: /home/vagrant/.rbenv/plugins/ruby-build

    - name: setup ruby-build
      shell: "{{ item }}"
      args:
        chdir: /home/vagrant
        executable: /bin/bash
      with_items:
        - echo 'export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"' >> ~/.bashrc
        - exec $SHELL

    - name: install ruby using rbenv
      remote_user: vagrant
      shell: "{{ item }}"
      args:
        chdir: /home/vagrant
        executable: /bin/bash
      with_items:
        - ${HOME}/.rbenv/bin/rbenv install 2.4.0
        - ${HOME}/.rbenv/bin/rbenv global 2.4.0


